### ISSUE TITLE
Compte membre - inscription

### ISSUE THREAD

**Issue by MWCorentin** [eusaintvincent/Livres-Blancs#5]
Fonctionnalités : 
----------------------------

- [ ] Inscription obligatoire pour télécharger, noter ou commenter

- [x] Inscription rapide par compte "facebook, twitter, linked in google +

- [x] Inscription manuelle (obligatoire: genre, nom, prénom, date de naissance, adresse mail)

**Comment by anbaut** [comment]
-Ajouter une case à cocher " J'accepte de recevoir des offres des partenaires de Livres-Blancs par email"
(Ne pas précocher la case)
